In [1]:
from sklearn import datasets

In [2]:
irisData = datasets.load_iris()
type(irisData)

sklearn.datasets.base.Bunch

In [3]:
print(irisData.data)

[[ 5.1  3.5  1.4  0.2]
 [ 4.9  3.   1.4  0.2]
 [ 4.7  3.2  1.3  0.2]
 [ 4.6  3.1  1.5  0.2]
 [ 5.   3.6  1.4  0.2]
 [ 5.4  3.9  1.7  0.4]
 [ 4.6  3.4  1.4  0.3]
 [ 5.   3.4  1.5  0.2]
 [ 4.4  2.9  1.4  0.2]
 [ 4.9  3.1  1.5  0.1]
 [ 5.4  3.7  1.5  0.2]
 [ 4.8  3.4  1.6  0.2]
 [ 4.8  3.   1.4  0.1]
 [ 4.3  3.   1.1  0.1]
 [ 5.8  4.   1.2  0.2]
 [ 5.7  4.4  1.5  0.4]
 [ 5.4  3.9  1.3  0.4]
 [ 5.1  3.5  1.4  0.3]
 [ 5.7  3.8  1.7  0.3]
 [ 5.1  3.8  1.5  0.3]
 [ 5.4  3.4  1.7  0.2]
 [ 5.1  3.7  1.5  0.4]
 [ 4.6  3.6  1.   0.2]
 [ 5.1  3.3  1.7  0.5]
 [ 4.8  3.4  1.9  0.2]
 [ 5.   3.   1.6  0.2]
 [ 5.   3.4  1.6  0.4]
 [ 5.2  3.5  1.5  0.2]
 [ 5.2  3.4  1.4  0.2]
 [ 4.7  3.2  1.6  0.2]
 [ 4.8  3.1  1.6  0.2]
 [ 5.4  3.4  1.5  0.4]
 [ 5.2  4.1  1.5  0.1]
 [ 5.5  4.2  1.4  0.2]
 [ 4.9  3.1  1.5  0.1]
 [ 5.   3.2  1.2  0.2]
 [ 5.5  3.5  1.3  0.2]
 [ 4.9  3.1  1.5  0.1]
 [ 4.4  3.   1.3  0.2]
 [ 5.1  3.4  1.5  0.2]
 [ 5.   3.5  1.3  0.3]
 [ 4.5  2.3  1.3  0.3]
 [ 4.4  3.2  1.3  0.2]
 [ 5.   3.5

In [8]:
print(irisData.feature_names)
print(irisData.target)
print(irisData.target_names)

['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]
['setosa' 'versicolor' 'virginica']


In [9]:
from sklearn.neighbors import KNeighborsClassifier
import numpy as np

In [10]:
idx = np.arange(len(irisData.data))

In [27]:
np.random.shuffle(idx)
trainData = irisData.data[idx[:120]]
trainLabel = irisData.target[idx[:120]]
testData = irisData.data[idx[120:]]
testLabel = irisData.target[idx[120:]]
print(testLabel)

[0 0 2 1 1 0 2 2 0 1 0 1 1 1 1 1 1 2 0 2 1 1 1 0 2 2 1 2 0 2]


In [28]:
knn = KNeighborsClassifier()

In [29]:
knn.fit(trainData,trainLabel)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=1, n_neighbors=5, p=2,
           weights='uniform')

In [30]:
predicted = knn.predict(testData)

In [31]:
print((testLabel==predicted).sum())

28

In [32]:
from sklearn import svm

In [33]:
svc=svm.SVC()
svc.fit(trainData,trainLabel)

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape=None, degree=3, gamma='auto', kernel='rbf',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

In [34]:
predicted = svc.predict(testData)
print((testLabel==predicted).sum())

30


In [35]:
from sklearn.ensemble import AdaBoostClassifier

In [40]:
for num in np.arange(1,20,1):
    adaDiscrete = AdaBoostClassifier(
        n_estimators=num,
        algorithm="SAMME")
    adaDiscrete.fit(trainData, trainLabel)
    predTrain = adaDiscrete.predict(trainData)
    wrongTrain = (trainLabel!= predTrain).sum()
    predTest = adaDiscrete.predict(testData)
    wrongTest = (testLabel != predTest).sum()
    print num,wrongTrain,wrongTest

1 37 13
2 41 9
3 3 4
4 3 4
5 3 4
6 3 4
7 4 2
8 3 4
9 2 2
10 3 4
11 2 2
12 2 2
13 2 2
14 2 2
15 2 2
16 2 2
17 0 2
18 0 2
19 0 2
